import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react-swc';
import path from 'path';

export default defineConfig({
    plugins: [react()] as any,
    test: {
        globals: true,
        environment: 'jsdom',
        setupFiles: './src/test/setup.ts',
        css: true,
        exclude: ['**/node_modules/**', '**/e2e/**'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json', 'html'],
            // `all` + an explicit include is what makes this number mean
            // anything. Without them v8 only reports files some test already
            // imports, so the 127 untested components are simply absent from
            // the denominator and the figure reads far better than the truth:
            // measured 2026-08-11: 33.63% statements that way, 16.62% counting
            // the whole of src/. Same suite, same day — only the denominator
            // differs.
            all: true,
            include: ['src/**/*.{ts,tsx}'],
            exclude: [
                'node_modules/',
                'src/test/',
                '**/*.test.{ts,tsx}',
                '**/*.spec.{ts,tsx}',
                // Generated by `supabase gen types` — never hand-written, so
                // covering it would measure the generator, not this codebase.
                'src/integrations/supabase/types.ts',
                // Bootstrap and type-only modules: no branches to exercise.
                'src/main.tsx',
                'src/vite-env.d.ts',
                '**/*.d.ts',
            ],
        },
    },
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
    },
});
