"""Cross-check the round-3 migration against the live snapshot, then emit rollback.sql.

Reads: the migration, before/pg_policies-live.csv (live pg_policies), and the
round-2 a01/remaining-write-policies.csv. Writes before/rollback.sql. Exits 1 on
any mismatch.
"""
import csv, json, re, sys
MIG = 'supabase/migrations/20261007183000_member_writes_follow_role_permissions.sql'
SNAP = 'evidence/report/2026-10-07-kpi7-round3/before/snapshot-rows.json'
R2 = 'evidence/report/2026-10-07-kpi7-round2/a01/remaining-write-policies.csv'
OUT = 'evidence/report/2026-10-07-kpi7-round3/before/rollback.sql'

sql = open(MIG).read()
drops = re.findall(r'^DROP POLICY "([^"]+)" ON (\w+)\.(\w+);', sql, re.M)
creates = re.findall(r'^CREATE POLICY "([^"]+)" ON (\w+)\.(\w+)', sql, re.M)
rows = {(r['schemaname'], r['tablename'], r['policyname']): r for r in json.load(open(SNAP))}
bad = 0
for name, sch, tbl in drops:
    r = rows.get((sch, tbl, name))
    if r is None: print('DROP target not in live snapshot:', sch, tbl, name); bad += 1
    elif r['cmd'] == 'SELECT': print('DROP target is a SELECT policy:', tbl, name); bad += 1
    elif 'has_role' in r['create_sql'] and 'is_team_member' not in r['create_sql']: print('DROP target is a staff policy:', tbl, name); bad += 1
dropped = {(t, n) for n, s, t in drops}
r2 = {(r['tablename'], r['policyname']) for r in csv.DictReader(open(R2))}
missing = r2 - dropped
extra = {d for d in dropped if d not in r2}
print(f'drops={len(drops)} creates={len(creates)} round2_rows={len(r2)}')
print('round-2 rows NOT dropped:', sorted(missing))
print('dropped but not in round-2 list:', sorted(extra))
# a CREATE whose name collides with a policy that survives on the same table
for name, sch, tbl in creates:
    if (sch, tbl, name) in rows and (name, sch, tbl) not in drops:
        print('CREATE collides with a surviving policy:', tbl, name); bad += 1
if bad: sys.exit(1)

with open(OUT, 'w') as f:
    f.write('-- ROLLBACK for 20261007183000_member_writes_follow_role_permissions.sql\n'
            '--\n-- NOT a migration. Generated by before/build_rollback.py from the live pg_policies\n'
            '-- snapshot taken BEFORE the push (before/snapshot-rows.json, 2026-10-07). Running it\n'
            '-- restores the A01 viewer-write hole on every table the migration touched; use only\n'
            '-- to undo the fix deliberately. Idempotent: new policies are dropped IF EXISTS, the\n'
            '-- originals are re-created after a DROP IF EXISTS of the same name.\n\nBEGIN;\n\n'
            '-- 1. Policies created by the migration.\n')
    for name, sch, tbl in creates:
        f.write(f'DROP POLICY IF EXISTS "{name}" ON {sch}.{tbl};\n')
    f.write('\n-- 2. The policies the migration dropped, verbatim from the snapshot.\n')
    for name, sch, tbl in drops:
        f.write(f'DROP POLICY IF EXISTS "{name}" ON {sch}.{tbl};\n{rows[(sch, tbl, name)]["create_sql"]}\n\n')
    f.write('COMMIT;\n')
print('wrote', OUT)
