-- ROLLBACK for 20261007183000_member_writes_follow_role_permissions.sql
--
-- NOT a migration. Generated by before/build_rollback.py from the live pg_policies
-- snapshot taken BEFORE the push (before/snapshot-rows.json, 2026-10-07). Running it
-- restores the A01 viewer-write hole on every table the migration touched; use only
-- to undo the fix deliberately. Idempotent: new policies are dropped IF EXISTS, the
-- originals are re-created after a DROP IF EXISTS of the same name.

BEGIN;

-- 1. Policies created by the migration.
DROP POLICY IF EXISTS "team_manage_settings_insert" ON public.workspace_api_keys;
DROP POLICY IF EXISTS "team_manage_settings_update" ON public.workspace_api_keys;
DROP POLICY IF EXISTS "team_manage_settings_delete" ON public.workspace_api_keys;
DROP POLICY IF EXISTS "import_jobs_insert" ON public.import_jobs;
DROP POLICY IF EXISTS "imports_insert_policy" ON storage.objects;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.ads;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.ads;
DROP POLICY IF EXISTS "team_delete_campaigns_delete" ON public.ads;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.ad_groups;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.ad_groups;
DROP POLICY IF EXISTS "team_delete_campaigns_delete" ON public.ad_groups;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.campaigns;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.campaigns;
DROP POLICY IF EXISTS "team_delete_campaigns_delete" ON public.campaigns;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.campaign_ads;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.campaign_ads;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.campaign_ads;
DROP POLICY IF EXISTS "Users can view campaign tags for their team" ON public.campaign_tags;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.campaign_tags;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.campaign_tags;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.campaign_tags;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.tags;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.tags;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.tags;
DROP POLICY IF EXISTS "team_manage_settings_insert" ON public.budgets;
DROP POLICY IF EXISTS "team_manage_settings_update" ON public.budgets;
DROP POLICY IF EXISTS "team_manage_settings_delete" ON public.budgets;
DROP POLICY IF EXISTS "team_edit_prospects_insert" ON public.workspace_ad_persona;
DROP POLICY IF EXISTS "team_edit_prospects_update" ON public.workspace_ad_persona;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.ad_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.ad_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.ad_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.post_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.post_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.post_personas;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.social_posts;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.social_posts;
DROP POLICY IF EXISTS "team_edit_campaigns_insert" ON public.social_comments;
DROP POLICY IF EXISTS "team_edit_campaigns_update" ON public.social_comments;
DROP POLICY IF EXISTS "team_edit_campaigns_delete" ON public.social_comments;
DROP POLICY IF EXISTS "team_export_data_insert" ON public.reports;
DROP POLICY IF EXISTS "team_export_data_update" ON public.reports;
DROP POLICY IF EXISTS "team_export_data_insert" ON public.scheduled_reports;
DROP POLICY IF EXISTS "team_export_data_update" ON public.scheduled_reports;
DROP POLICY IF EXISTS "team_export_data_delete" ON public.scheduled_reports;
DROP POLICY IF EXISTS "team_export_data_insert" ON public.email_campaigns;
DROP POLICY IF EXISTS "team_export_data_update" ON public.email_campaigns;
DROP POLICY IF EXISTS "team_export_data_delete" ON public.email_campaigns;
DROP POLICY IF EXISTS "team_member_insert_own" ON public.team_activity_logs;

-- 2. The policies the migration dropped, verbatim from the snapshot.
DROP POLICY IF EXISTS "Team members can insert API keys" ON public.workspace_api_keys;
CREATE POLICY "Team members can insert API keys" ON public.workspace_api_keys AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((EXISTS ( SELECT 1
   FROM workspace_members
  WHERE ((workspace_members.team_id = workspace_api_keys.team_id) AND (workspace_members.user_id = ( SELECT auth.uid() AS uid))))) OR (EXISTS ( SELECT 1
   FROM workspaces
  WHERE ((workspaces.id = workspace_api_keys.team_id) AND (workspaces.owner_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "Team members can update API keys" ON public.workspace_api_keys;
CREATE POLICY "Team members can update API keys" ON public.workspace_api_keys AS PERMISSIVE FOR UPDATE TO public
  USING (((EXISTS ( SELECT 1
   FROM workspace_members
  WHERE ((workspace_members.team_id = workspace_api_keys.team_id) AND (workspace_members.user_id = ( SELECT auth.uid() AS uid))))) OR (EXISTS ( SELECT 1
   FROM workspaces
  WHERE ((workspaces.id = workspace_api_keys.team_id) AND (workspaces.owner_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "Team members can delete API keys" ON public.workspace_api_keys;
CREATE POLICY "Team members can delete API keys" ON public.workspace_api_keys AS PERMISSIVE FOR DELETE TO public
  USING (((EXISTS ( SELECT 1
   FROM workspace_members
  WHERE ((workspace_members.team_id = workspace_api_keys.team_id) AND (workspace_members.user_id = ( SELECT auth.uid() AS uid))))) OR (EXISTS ( SELECT 1
   FROM workspaces
  WHERE ((workspaces.id = workspace_api_keys.team_id) AND (workspaces.owner_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "import_jobs_insert" ON public.import_jobs;
CREATE POLICY import_jobs_insert ON public.import_jobs AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((is_team_member(( SELECT auth.uid() AS uid), team_id) AND (uploaded_by = ( SELECT auth.uid() AS uid))));

DROP POLICY IF EXISTS "imports_insert_policy" ON storage.objects;
CREATE POLICY imports_insert_policy ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'imports'::text) AND is_team_member(auth.uid(), try_cast_uuid((storage.foldername(name))[1]))));

DROP POLICY IF EXISTS "Users can insert ads if team member" ON public.ads;
CREATE POLICY "Users can insert ads if team member" ON public.ads AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "Users can update ads if team member" ON public.ads;
CREATE POLICY "Users can update ads if team member" ON public.ads AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)))
  WITH CHECK ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "Users can delete ads if team member" ON public.ads;
CREATE POLICY "Users can delete ads if team member" ON public.ads AS PERMISSIVE FOR DELETE TO authenticated
  USING ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "Users can insert ad_groups if team member" ON public.ad_groups;
CREATE POLICY "Users can insert ad_groups if team member" ON public.ad_groups AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "Users can update ad_groups if team member" ON public.ad_groups;
CREATE POLICY "Users can update ad_groups if team member" ON public.ad_groups AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)))
  WITH CHECK ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "Users can delete ad_groups if team member" ON public.ad_groups;
CREATE POLICY "Users can delete ad_groups if team member" ON public.ad_groups AS PERMISSIVE FOR DELETE TO authenticated
  USING ((is_team_member(( SELECT auth.uid() AS uid), team_id) OR has_role(( SELECT auth.uid() AS uid), 'admin'::app_role)));

DROP POLICY IF EXISTS "team_campaigns_insert" ON public.campaigns;
CREATE POLICY team_campaigns_insert ON public.campaigns AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "team_campaigns_update" ON public.campaigns;
CREATE POLICY team_campaigns_update ON public.campaigns AS PERMISSIVE FOR UPDATE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "team_campaigns_delete" ON public.campaigns;
CREATE POLICY team_campaigns_delete ON public.campaigns AS PERMISSIVE FOR DELETE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "campaign_ads_write" ON public.campaign_ads;
CREATE POLICY campaign_ads_write ON public.campaign_ads AS PERMISSIVE FOR ALL TO public
  USING ((campaign_id IN ( SELECT campaigns.id
   FROM campaigns
  WHERE (campaigns.team_id IN ( SELECT workspace_members.team_id
           FROM workspace_members
          WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))))))
  WITH CHECK ((campaign_id IN ( SELECT campaigns.id
   FROM campaigns
  WHERE (campaigns.team_id IN ( SELECT workspace_members.team_id
           FROM workspace_members
          WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "Users can manage campaign tags for their team" ON public.campaign_tags;
CREATE POLICY "Users can manage campaign tags for their team" ON public.campaign_tags AS PERMISSIVE FOR ALL TO public
  USING ((campaign_id IN ( SELECT c.id
   FROM (campaigns c
     JOIN ad_accounts aa ON ((c.ad_account_id = aa.id)))
  WHERE (aa.team_id IN ( SELECT workspaces.id
           FROM workspaces
          WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
        UNION
         SELECT workspace_members.team_id
           FROM workspace_members
          WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "Users can insert their team tags" ON public.tags;
CREATE POLICY "Users can insert their team tags" ON public.tags AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can update their team tags" ON public.tags;
CREATE POLICY "Users can update their team tags" ON public.tags AS PERMISSIVE FOR UPDATE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can delete their team tags" ON public.tags;
CREATE POLICY "Users can delete their team tags" ON public.tags AS PERMISSIVE FOR DELETE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can insert their team budgets" ON public.budgets;
CREATE POLICY "Users can insert their team budgets" ON public.budgets AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can update their team budgets" ON public.budgets;
CREATE POLICY "Users can update their team budgets" ON public.budgets AS PERMISSIVE FOR UPDATE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can delete their team budgets" ON public.budgets;
CREATE POLICY "Users can delete their team budgets" ON public.budgets AS PERMISSIVE FOR DELETE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "personas_insert_policy" ON public.customer_personas;
CREATE POLICY personas_insert_policy ON public.customer_personas AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM workspaces w
  WHERE ((w.id = customer_personas.team_id) AND ((w.owner_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
           FROM workspace_members wm
          WHERE ((wm.team_id = w.id) AND (wm.user_id = ( SELECT auth.uid() AS uid))))))))));

DROP POLICY IF EXISTS "personas_update_policy" ON public.customer_personas;
CREATE POLICY personas_update_policy ON public.customer_personas AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM workspaces w
  WHERE ((w.id = customer_personas.team_id) AND ((w.owner_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
           FROM workspace_members wm
          WHERE ((wm.team_id = w.id) AND (wm.user_id = ( SELECT auth.uid() AS uid))))))))));

DROP POLICY IF EXISTS "personas_delete_policy" ON public.customer_personas;
CREATE POLICY personas_delete_policy ON public.customer_personas AS PERMISSIVE FOR DELETE TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM workspaces w
  WHERE ((w.id = customer_personas.team_id) AND ((w.owner_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
           FROM workspace_members wm
          WHERE ((wm.team_id = w.id) AND (wm.user_id = ( SELECT auth.uid() AS uid))))))))));

DROP POLICY IF EXISTS "Workspace members can insert workspace_ad_persona" ON public.workspace_ad_persona;
CREATE POLICY "Workspace members can insert workspace_ad_persona" ON public.workspace_ad_persona AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), workspace_id));

DROP POLICY IF EXISTS "Workspace members can update workspace_ad_persona" ON public.workspace_ad_persona;
CREATE POLICY "Workspace members can update workspace_ad_persona" ON public.workspace_ad_persona AS PERMISSIVE FOR UPDATE TO public
  USING (is_team_member(( SELECT auth.uid() AS uid), workspace_id));

DROP POLICY IF EXISTS "ad_personas_write" ON public.ad_personas;
CREATE POLICY ad_personas_write ON public.ad_personas AS PERMISSIVE FOR ALL TO authenticated
  USING ((ad_id IN ( SELECT ads.id
   FROM ads
  WHERE (ads.team_id IN ( SELECT workspace_members.team_id
           FROM workspace_members
          WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid))
        UNION
         SELECT workspaces.id
           FROM workspaces
          WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "post_personas_write" ON public.post_personas;
CREATE POLICY post_personas_write ON public.post_personas AS PERMISSIVE FOR ALL TO authenticated
  USING ((post_id IN ( SELECT social_posts.id
   FROM social_posts
  WHERE (social_posts.team_id IN ( SELECT workspace_members.team_id
           FROM workspace_members
          WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid))
        UNION
         SELECT workspaces.id
           FROM workspaces
          WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid)))))));

DROP POLICY IF EXISTS "Team members can create social posts" ON public.social_posts;
CREATE POLICY "Team members can create social posts" ON public.social_posts AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "Team members can update social posts" ON public.social_posts;
CREATE POLICY "Team members can update social posts" ON public.social_posts AS PERMISSIVE FOR UPDATE TO public
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "social_comments_insert" ON public.social_comments;
CREATE POLICY social_comments_insert ON public.social_comments AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "social_comments_update" ON public.social_comments;
CREATE POLICY social_comments_update ON public.social_comments AS PERMISSIVE FOR UPDATE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id))
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "social_comments_delete" ON public.social_comments;
CREATE POLICY social_comments_delete ON public.social_comments AS PERMISSIVE FOR DELETE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "Team members can create reports" ON public.reports;
CREATE POLICY "Team members can create reports" ON public.reports AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "Team members can update reports" ON public.reports;
CREATE POLICY "Team members can update reports" ON public.reports AS PERMISSIVE FOR UPDATE TO public
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "Users can insert their team scheduled reports" ON public.scheduled_reports;
CREATE POLICY "Users can insert their team scheduled reports" ON public.scheduled_reports AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can update their team scheduled reports" ON public.scheduled_reports;
CREATE POLICY "Users can update their team scheduled reports" ON public.scheduled_reports AS PERMISSIVE FOR UPDATE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can delete their team scheduled reports" ON public.scheduled_reports;
CREATE POLICY "Users can delete their team scheduled reports" ON public.scheduled_reports AS PERMISSIVE FOR DELETE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can insert their team email campaigns" ON public.email_campaigns;
CREATE POLICY "Users can insert their team email campaigns" ON public.email_campaigns AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can update their team email campaigns" ON public.email_campaigns;
CREATE POLICY "Users can update their team email campaigns" ON public.email_campaigns AS PERMISSIVE FOR UPDATE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "Users can delete their team email campaigns" ON public.email_campaigns;
CREATE POLICY "Users can delete their team email campaigns" ON public.email_campaigns AS PERMISSIVE FOR DELETE TO public
  USING ((team_id IN ( SELECT workspaces.id
   FROM workspaces
  WHERE (workspaces.owner_id = ( SELECT auth.uid() AS uid))
UNION
 SELECT workspace_members.team_id
   FROM workspace_members
  WHERE (workspace_members.user_id = ( SELECT auth.uid() AS uid)))));

DROP POLICY IF EXISTS "sync_history_insert" ON public.sync_history;
CREATE POLICY sync_history_insert ON public.sync_history AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "sync_history_update" ON public.sync_history;
CREATE POLICY sync_history_update ON public.sync_history AS PERMISSIVE FOR UPDATE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id))
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "sync_history_delete" ON public.sync_history;
CREATE POLICY sync_history_delete ON public.sync_history AS PERMISSIVE FOR DELETE TO authenticated
  USING (is_team_member(( SELECT auth.uid() AS uid), team_id));

DROP POLICY IF EXISTS "team_member_insert" ON public.conversion_events;
CREATE POLICY team_member_insert ON public.conversion_events AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM ad_accounts aa
  WHERE ((aa.id = conversion_events.ad_account_id) AND is_team_member(( SELECT auth.uid() AS uid), aa.team_id)))));

DROP POLICY IF EXISTS "System can insert activity logs" ON public.team_activity_logs;
CREATE POLICY "System can insert activity logs" ON public.team_activity_logs AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (is_team_member(( SELECT auth.uid() AS uid), team_id));

COMMIT;
